version: "3.8"
services:
  db:
    image: mysql:8
    container_name: app-db
    ports:
      - 127.0.0.1:${DB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--user=$${DB_USER}", "--password=$${DB_PASSWORD}" ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5

  node:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-node
    ports:
      - 127.0.0.1:${PORT}:${PORT}
    volumes:
      - /home/node/app/node_modules
      - ./:/home/node/app
    networks:
      - app-network
    env_file: ./.env
    restart: always
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
    name: app-db-data

networks:
  app-network:
    driver: bridge
